### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by randyli** [XiaoMi/linden#6]
when i compile and run the demo, it give me a  http error. It seems that lose some libs 

HTTP ERROR 500
Problem accessing /. Reason:

    Server Error
Caused by:
org.apache.jasper.JasperException: PWC6033: Error in Javac compilation for JSP

PWC6199: Generated servlet error:
package org.apache.jasper.runtime does not exist

PWC6199: Generated servlet error:
package org.apache.jasper.runtime does not exist

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class JspFactory
  location: class org.apache.jsp.WEB_002dINF.views.index_jsp

PWC6199: Generated servlet error:
package org.glassfish.jsp.api does not exist

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class HttpServletRequest
  location: class org.apache.jsp.WEB_002dINF.views.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class HttpServletResponse
  location: class org.apache.jsp.WEB_002dINF.views.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class ServletException
  location: class org.apache.jsp.WEB_002dINF.views.index_jsp

PWC6199: Generated servlet error:
package javax.servlet does not exist

PWC6199: Generated servlet error:
package javax.servlet.http does not exist

PWC6199: Generated servlet error:
package javax.servlet.jsp does not exist

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   variable JspFactory
  location: class org.apache.jsp.WEB_002dINF.views.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class PageContext
  location: class org.apache.jsp.WEB_002dINF.views.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class HttpSession
  location: class org.apache.jsp.WEB_002dINF.views.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class ServletContext
  location: class org.apache.jsp.WEB_002dINF.views.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class ServletConfig
  location: class org.apache.jsp.WEB_002dINF.views.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class JspWriter
  location: class org.apache.jsp.WEB_002dINF.views.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class JspWriter
  location: class org.apache.jsp.WEB_002dINF.views.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class PageContext
  location: class org.apache.jsp.WEB_002dINF.views.index_jsp

PWC6199: Generated servlet error:
package org.glassfish.jsp.api does not exist

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class SkipPageException
  location: class org.apache.jsp.WEB_002dINF.views.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class ServletException
  location: class org.apache.jsp.WEB_002dINF.views.index_jsp

	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:129)
	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:299)
	at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:392)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:453)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:625)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:375)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:738)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:586)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:478)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:261)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:101)
	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:209)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:266)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1225)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1012)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:876)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:852)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:738)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:568)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:478)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:462)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by randyli** [comment]
jdk 11

**Comment by sergoss** [comment]
> jdk 11

Hello! Do you have find to resolve this issue?
